# Generated by Django 5.1.1 on 2025-02-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$10dI3qtmdoHSV9JA60MkD1$CegIptNHJhN4IDrYAnedXi4GDHNP5a4e+dR3oGdAgfU=', max_length=128),
        ),
    ]
