# Generated by Django 5.1.1 on 2025-02-26 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_employee_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_assets', to='myapp.employee'),
        ),
        migrations.AddField(
            model_name='asset',
            name='initiator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_assets', to='myapp.employee'),
        ),
        migrations.AddField(
            model_name='asset',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$J1CKg08NSwadk5n050VIN2$UMwsO+sfVkLmDqSehKotHBZrVDBMeSWvuC7U8QKJ8Zw=', max_length=128),
        ),
    ]
