# Generated by Django 5.1.1 on 2025-02-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_employee_password_assetmovement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$WYCvLcyKSs7ZpNqlQPl7Q9$N/f91/LWEWb7FREV46a4s/IMxPxjdoJ/EyrvdTKH9rw=', max_length=128),
        ),
    ]
