# Generated by Django 5.1.1 on 2025-02-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_employee_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$n0i2n8AbONK25mTdXFJbX5$700hRlPaspW1fnWtIDIrgLnOGF9JEvWOmu2oQFBsZF8=', max_length=128),
        ),
    ]
