# Generated by Django 5.1.1 on 2025-02-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_asset_serial_number_alter_employee_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$2KSmm0Gme7xPBNJkJzayGt$H1VeGboEIwXOxWCw1FmO2RK7C8YWjSBx2VuxpKadDjY=', max_length=128),
        ),
    ]
