# Generated by Django 5.1.1 on 2025-02-27 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_employee_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmovement',
            name='attachment',
            field=models.FileField(blank=True, help_text='Upload any relevant documents (e.g., transfer forms, repair reports)', null=True, upload_to='movement_attachments/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$yGZY9PLRrWUVvHbVJwBMRq$sSiOMWk2afaPkmzF6ATzn0belZhIv2kukU16n5NLHfw=', max_length=128),
        ),
    ]
