# Generated by Django 5.1.1 on 2025-02-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_assetmovement_attachment_alter_employee_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('permissions', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(
                default='pbkdf2_sha256$870000$zm39tBFjg4r8Eck8M4ovzX$QAfdJ/YZHl0U4RJfy/97fpSMYpqp0K4ROPwGGGM4+6U=', max_length=128),
        ),
        migrations.AddField(
            model_name='employee',
            name='roles',
            field=models.ManyToManyField(blank=True, to='myapp.role'),
        ),
    ]
