# Generated by Django 5.1.1 on 2025-02-27 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_role_alter_employee_password_employee_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmovement',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetmovement',
            name='approver',
            field=models.ForeignKey(blank=True, help_text='Employee who approved or rejected this movement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_movements', to='myapp.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$OHILnmwxgyat6LwRDG0fHE$+LPNcgMmHi1dQvJi3vd3MQPTfYFMMFKcFavSZxXexfs=', max_length=128),
        ),
    ]
