from django.urls import path
from . import views

urlpatterns = [
    path('', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('forgot-password/', views.forgot_password, name='forgot_password'),
    path('reset-password/', views.reset_password, name='reset_password'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('system-management/', views.system_management_home,
         name='system_management'),
    path('add-employee/', views.add_employee, name='add_employee'),
    path('edit-employee/<int:employee_id>/',
         views.edit_employee, name='edit_employee'),
    path('toggle-employee-status/<int:employee_id>/',
         views.toggle_employee_status, name='toggle_employee_status'),
    path('add-department/', views.add_department, name='add_department'),
    path('toggle-department-status/<int:department_id>/',
         views.toggle_department_status, name='toggle_department_status'),
    path('employee-management/', views.employee_management,
         name='employee_management'),
    path('department-management/', views.department_management,
         name='department_management'),
    path('asset-management/', views.asset_management, name='asset_management'),
    path('add-asset/', views.add_asset, name='add_asset'),
    path('edit-asset/<int:asset_id>/', views.edit_asset, name='edit_asset'),
    path('toggle-asset-status/<int:asset_id>/',
         views.toggle_asset_status, name='toggle_asset_status'),
    path('delete-asset/<int:asset_id>/',
         views.delete_asset, name='delete_asset'),
    path('asset-register/', views.asset_register, name='asset_register'),
    path('asset-movement/', views.asset_movement, name='asset_movement'),
    path('create-movement/', views.create_movement, name='create_movement'),
    path('approve-movement/<int:movement_id>/',
         views.approve_movement, name='approve_movement'),
    path('reject-movement/<int:movement_id>/',
         views.reject_movement, name='reject_movement'),
    path('movement-details/<int:movement_id>/',
         views.movement_details, name='movement_details'),
    path('movement-approvals/', views.movement_approvals,
         name='movement_approvals'),
    path('movement-history/', views.movement_history, name='movement_history'),
    path('it-management/', views.it_management, name='it_management'),
    path('role-management/', views.role_management, name='role_management'),
    path('add-role/', views.add_role, name='add_role'),
    path('edit-role/<int:role_id>/', views.edit_role, name='edit_role'),
    path('get-role-data/<int:role_id>/',
         views.get_role_data, name='get_role_data'),
    path('toggle-role-status/<int:role_id>/',
         views.toggle_role_status, name='toggle_role_status'),
    path('get-role-users/<int:role_id>/',
         views.get_role_users, name='get_role_users'),
    path('assign-users-to-role/', views.assign_users_to_role,
         name='assign_users_to_role'),
    path('schedule-maintenance/', views.schedule_maintenance,
         name='schedule_maintenance'),
    path('update-maintenance-status/<int:maintenance_id>/',
         views.update_maintenance_status, name='update_maintenance_status'),
    path('get-asset-maintenance-history/<str:asset_id>/',
         views.get_asset_maintenance_history, name='get_asset_maintenance_history'),
]
